on:
  push:
    branches: main
  pull_request:
    branches: main

name: R CMD Check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: 'devel'}
          - {os: macOS-latest, r: 'release'}
          - {os: windows-latest, r: 'devel'}
          - {os: windows-latest, r: 'release'}
          - {os: windows-latest, r: 'oldrel'}
          - {os: ubuntu-22.04, r: 'devel'}
          - {os: ubuntu-22.04, r: 'release'}
          - {os: ubuntu-22.04, r: 'oldrel'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_DONTTEST_EXAMPLES_: false
      SPECIESPLUS_TOKEN: ${{ secrets.SPECIESPLUS_TOKEN }}
      CRAN: ${{ matrix.config.cran }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::covr
            any::goodpractice
          needs: check

      - name: Good practices
        run: |
          goodpractice::gp(checks = c(
            "cyclocomp",
            "no_import_package_as_a_whole",
            "no_export_pattern"
          ))
        shell: Rscript {0}

      - uses: r-lib/actions/check-r-package@v2

      - name: Test coverage
        if: matrix.config.os == 'ubuntu-22.04' && matrix.config.r == 'release'
        run: |
          install.packages(c("remotes", "covr"))
          covr::codecov(token = "${{secrets.CODECOV_TOKEN}}")
        shell: Rscript {0}
